{
 "title": "NFS 流量追踪-服务器视角",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "nfs_server",
    "query": "label_values(nfs_read_count, nfs_server)"
   },
   {
    "name": "expose_dir",
    "query": "label_values(nfs_read_count{nfs_server=~\"$nfs_server:.*\"}, nfs_server)"
   },
   { "name": "rate_range", "query": "5m,10m,30m,1h,3h,6h,24h" }
  ]
 },
 "panels": [
  {
   "title": "写 IOPS TOP 10",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(10, sum by(file_path) (irate(nfs_write_count{nfs_server=~\"$nfs_server:.*\", nfs_server=~\".*$expose_dir.*\"}[$rate_range])>0))"
    }
   ]
  },
  {
   "title": "写流量 TOP 10",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(10, sum by(file_path) (irate(nfs_write_size{nfs_server=~\"$nfs_server:.*\", nfs_server=~\".*$expose_dir.*\"}[$rate_range])>0))"
    }
   ]
  },
  {
   "title": "写延迟 TOP 10",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "topk(10, sum by(file_path) (irate(nfs_write_latencies{nfs_server=~\"$nfs_server:.*\", nfs_server=~\".*$expose_dir.*\"}[$rate_range])>0))"
    }
   ]
  },
  {
   "title": "读 IOPS TOP 10",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "topk(10, sum by(file_path) (irate(nfs_read_count{nfs_server=~\"$nfs_server:.*\", nfs_server=~\".*$expose_dir.*\"}[$rate_range])>0))"
    }
   ]
  },
  {
   "title": "读流量 TOP 10",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(10, sum by(file_path) (irate(nfs_read_size{nfs_server=~\"$nfs_server:.*\", nfs_server=~\".*$expose_dir.*\"}[$rate_range])>0))"
    }
   ]
  },
  {
   "title": "读延迟 TOP 10",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "topk(10, sum by(file_path) (irate(nfs_read_latencies{nfs_server=~\"$nfs_server:.*\", nfs_server=~\".*$expose_dir.*\"}[$rate_range])>0))"
    }
   ]
  }
 ]
}