{
 "title": "NFS 流量追踪-客户端视角",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": "label_values(kube_pod_info, node)"
   },
   {
    "name": "pod",
    "query": "label_values({__name__=~\"nfs_write_count|nfs_read_count\",node_name=\"$node\"}, nfs_pod)"
   },
   {
    "name": "container",
    "query": "label_values({__name__=~\"nfs_write_count|nfs_read_count\",node_name=\"$node\",nfs_pod=\"$pod\"}, nfs_container)"
   }
  ]
 },
 "panels": [
  {
   "title": "NFS 总 IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum (irate(nfs_write_count{node_name=\"$node\"}[5m]))",
     "legendFormat": "write"
    },
    {
     "expr": "sum (irate(nfs_read_count{node_name=\"$node\"}[5m]))",
     "legendFormat": "read"
    }
   ]
  },
  {
   "title": "NFS 写延迟",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "irate(nfs_write_latencies{node_name=\"$node\",nfs_pod=\"$pod\",nfs_container=\"$container\"}[5m])",
     "legendFormat": "{{nfs_server}} {{file_path}}"
    }
   ]
  },
  {
   "title": "NFS 读延迟",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "irate(nfs_read_latencies{node_name=\"$node\",nfs_pod=\"$pod\",nfs_container=\"$container\"}[5m])",
     "legendFormat": "{{nfs_server}} {{file_path}}"
    }
   ]
  },
  {
   "title": "NFS 写流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "binBps" }
   ],
   "targets": [
    {
     "expr": "irate(nfs_write_size{node_name=\"$node\",nfs_pod=\"$pod\",nfs_container=\"$container\"}[5m])",
     "legendFormat": "{{nfs_server}} {{file_path}}"
    }
   ]
  },
  {
   "title": "NFS 读流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(nfs_read_size{node_name=\"$node\",nfs_pod=\"$pod\",nfs_container=\"$container\"}[5m])",
     "legendFormat": "{{nfs_server}} {{file_path}}"
    }
   ]
  },
  {
   "title": "NFS 写 IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nfs_write_count{node_name=\"$node\",nfs_pod=\"$pod\",nfs_container=\"$container\"}[5m])",
     "legendFormat": "{{nfs_server}} {{file_path}}"
    }
   ]
  },
  {
   "title": "NFS 读 IOPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nfs_read_count{node_name=\"$node\",nfs_pod=\"$pod\",nfs_container=\"$container\"}[5m])",
     "legendFormat": "{{nfs_server}} {{file_path}}"
    }
   ]
  }
 ]
}