{
 "title": "NFS Trace 看板",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum (irate(nfs_read_count[5m]))",
     "legendFormat": "read"
    },
    {
     "expr": "sum (irate(nfs_write_count[5m]))",
     "legendFormat": "write"
    }
   ]
  },
  {
   "title": "NFS 读延迟",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expr": "irate(nfs_read_latencies[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "NFS 读 IOPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    { "expr": "irate(nfs_read_count[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "读吞吐量",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "irate(nfs_read_size[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "NFS 写延迟",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    { "expr": "irate(nfs_write_latencies[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "NFS 写 IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
   "targets": [
    { "expr": "irate(nfs_write_count[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "写吞吐量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "irate(nfs_write_size[5m])", "legendFormat": "__auto" }
   ]
  }
 ]
}