name: Docker Image CI

on:
  push:
    branches: [ "ghostbaby" ]
  pull_request:
    branches: [ "ghostbaby" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: make image
